<a target="_blank" href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/LA_CP_01_Matrices.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# ЛА-Комп'ютерний практикум-01. Матриці

In [ ]:
# these imports may be useful

import pandas as pd
import numpy as np

 #### Деякі інструменти, які, можливо, стануть у нагоді.

In [ ]:
# these tools may be useful
# give a matrix
a = np.array([[1,2], [2,4], [3,6]]) #3x2 matrix
b = np.array([[1], [2]])            #2x1 matrix = column vector
c = np.array([[1,2], [2,3]])        #2x2 square matrix

#zero matrix
z = np.zeros((2, 3))

#matrix with all 1 elements
ones = np.ones((2,3))

# transpose
at = a.transpose()

# matrix multiplication
prod1 = a @ b
prod2 = np.matmul(a, b)

# dot (inner, scalar) product of vectors
u = np.array([1,2,3])
v = np.array([2,3,4])
uv = np.dot(u, v)

# inverse matrix
c_inv = np.linalg.inv(c)

print(f' zero={z},\n\n all 1-matrix={ones},\n\n a= {a},\n\n b = {b},\n\n,  c= {c}, \n\n a^t = {at},\n\n ab = {prod1}, \n\n ab= {prod2} \n')
print(f'u={u}, v={v}, uv = {uv} \n\n')
print(f'c = {c},\n\n c^(-1) = {c_inv}')

 zero=[[0. 0. 0.]
 [0. 0. 0.]],

 all 1-matrix=[[1. 1. 1.]
 [1. 1. 1.]],

 a= [[1 2]
 [2 4]
 [3 6]],

 b = [[1]
 [2]],

,  c= [[1 2]
 [2 3]], 

 a^t = [[1 2 3]
 [2 4 6]],

 ab = [[ 5]
 [10]
 [15]], 

 ab= [[ 5]
 [10]
 [15]] 

u=[1 2 3], v=[2 3 4], uv = 20 


c = [[1 2]
 [2 3]],

 c^(-1) = [[-3.  2.]
 [ 2. -1.]]


💻  **1.1. Перевірка властивостей**

Напишіть функції, які перевіряють чи є квадратна матриця
1) симетричною;
2) верхньотрикутною (нижньотрикутною);
3) діагональною;
4) скалярною

Якщо вам знадобиться порівнювати матриці, то треба використовувати функцію numpy.allclose, а не оператор порівняння $==$. Подумайте чому.

Знайдіть відповідні функції в numpy. Подивіться їх вихідний код та порівняйте з вашим.

In [26]:
#write your code here
import pandas as pd
import numpy as np

def is_symmetric_matrix(arr):
    arr_temp = arr.transpose()
    return np.allclose(arr, arr_temp)

def is_upper_triangular_matrix(arr):
    result = True

    for i_r, row in enumerate(arr):
      for i_c, col in enumerate(row):
        if i_r > 0 and i_c < i_r:
          if col != 0:
            result = False

    return result

def is_lower_triangular_matrix(arr):
    result = True

    for i_r, row in enumerate(arr):
      for i_c, col in enumerate(row):
        if i_r < len(arr) and i_c > i_r:
          if col != 0:
            result = False

    return result

def is_diagonal_matrix(arr):
    result = True

    for i_r, row in enumerate(arr):
      for i_c, col in enumerate(row):
        if i_r != i_c:
          if col != 0:
            result = False

    return result


def is_scalar_matrix(arr):
    n = len(arr)
    result = True
    for i in range(n):
        for j in range(n):
            if i == j:
                if arr[i][j] != arr[0][0]:
                    result = False
            else:
                if arr[i][j] != 0:
                    result = False

    return result

arr = np.array([
        [1, 0, 1],
        [0, 2, 5],
        [1, 5, 3]
        ])

arr2 = np.array([
        [1, 0, 1],
        [0, 2, 5],
        [0, 0, 3]
        ])

arr3 = np.array([
        [1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]
        ])

arr4 = np.array([
        [2, 0, 0],
        [0, 2, 0],
        [0, 0, 2]
        ])

print(is_symmetric_matrix(arr))
print(is_upper_triangular_matrix(arr2))
print(is_lower_triangular_matrix(arr2.transpose()))
print(is_diagonal_matrix(arr3))
print(is_scalar_matrix(arr4))



True
True
True
True
True


💻 **1.2. Діагоналі.**

Напишіть функцію diag\_matrix, яка отримує на вхід натуральне число $n$ і будує матрицю, на діагоналях якої стоять відповідно $0,1,2, \dots n, n-1, \dots 0$ . Наприклад, для $ n = 3 $ будує матрицю
$\left( \begin{array}{cccc} 3 & 2 & 1 & 0 \\ 2 & 3 & 2 & 1 \\ 1 & 2 & 3 & 2 \\ 0 & 1 & 2 & 3 \end{array} \right)$. Використовуйте засоби numpy, не використовуйте цикли та поелементне присвоєння.

In [28]:
#write your code here
import numpy as np

def diag_matrix(n):
    indices = np.arange(n + 1)

    diff_matrix = np.abs(indices[:, np.newaxis] - indices)

    result = n - diff_matrix

    return result

print(diag_matrix(3))

[[3 2 1 0]
 [2 3 2 1]
 [1 2 3 2]
 [0 1 2 3]]
[0 1 2 3]


💻 **1.3. Decorate matrix.**

Напишіть функцію decorate\_matrix, яка отримує на вхід матрицю $m\times n$ і ``обходить'' її одиницями. Наприклад, із матриці

$\left( \begin{array}{cc} 3 & 2 \\ 2 & 3 \end{array} \right)$ робить матрицю $\left( \begin{array}{cccc} 1 & 1 & 1 & 1 \\ 1 & 3 & 2 & 1 \\ 1 & 2 & 3 & 1 \\ 1 & 1 & 1 & 1 \end{array} \right)$. Використовуйте засоби numpy, не використовуйте цикли та поелементне присвоєння.

In [ ]:
#write your code here
import numpy as np

def decorate_matrix(matrix):
    return np.pad(matrix, pad_width=1, mode='constant', constant_values=1)

input_matrix = np.array([[3, 2],
                         [2, 3]])

result = decorate_matrix(input_matrix)
print(result)

💻 **1.4. Дії над матрицями.** Проілюструйте властивості матричних операцій, що подано нижче, на декількох прикладах. Матриці для прикладів можете обрати самостійно. Вкажіть у коментарях, які є обмеження на матриці, щоб властивості виконувалися.

1. $(A^t)^t=A$;
2. $(A+B)^t=A^t+B^t$;
3. $(A-B)^t=A^t-B^t$;
4. $(\lambda A)^t=\lambda A^t$;
5. $(AB)^t=B^tA^t$;
6. $(AB)^{-1}=B^{-1}A^{-1}$;
7. $(A^t)^{-1}=(A^{-1})^t$.


In [30]:
#write your code here
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
l = 5
# 1. Обмежень немає.
print(np.allclose((A.T).T, A))

# 2. Матриці повинні мати однаковий розмір
print(np.allclose((A + B).T, A.T + B.T))

# 3. Матриці повинні мати однаковий розмір
print(np.allclose((A - B).T, A.T - B.T))

# 4. Обмежень немає.
print(np.allclose((l * A).T, l * A.T))

# 5.
print(np.allclose((A @ B).T, B.T @ A.T))

# 6.
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
print(np.allclose(np.linalg.inv(A @ B), B_inv @ A_inv))

# 7.
print(np.allclose(np.linalg.inv(A.T), (np.linalg.inv(A)).T))


True
True
True
True
True
True
True


💻 **1.5. pandas - таблиці.** У практичних задачах матриці часто виникають при обробці табличних даних. Ця вправа -- знайомство з python-пакетом pandas, який використовують для роботи з таблицями. Для виконання вправ тримайте під рукою документацію pandas. Ви також можете питати штучний інтелект про потрібні функції, але щоб їх засвоїти, варто писати код самостійно.

1️⃣  Задайте таблицю, в якій будуть дані про деяких людей: Прізвище, Ім'я, Стать, Вік, Зріст, Країна. Подивіться в документації основні способи задання таблиць за допомогою pandas.DataFrame. Проілюструйте їх використання.


In [ ]:
#write your code here
import pandas as pd

data_rows = [
    ['Ivanenko', 'Ivan', 'M', 25, 180, 'Ukraine'],
    ['Petrenko', 'Olena', 'F', 30, 165, 'Poland'],
    ['Sydorenko', 'Dmytro', 'M', 22, 175, 'Ukraine']
]

columns_names = ['Last_Name', 'First_Name', 'Gender', 'Age', 'Height', 'Country']

df2 = pd.DataFrame(data_rows, columns=columns_names)
print("\nMethod 2 (List of rows):\n", df2)

data_records = [
    {'Last_Name': 'Ivanenko', 'First_Name': 'Ivan', 'Gender': 'M', 'Age': 25, 'Height': 180, 'Country': 'Ukraine'},
    {'Last_Name': 'Petrenko', 'First_Name': 'Olena', 'Gender': 'F', 'Age': 30, 'Height': 165, 'Country': 'Poland'},
    {'Last_Name': 'Sydorenko', 'First_Name': 'Dmytro', 'Gender': 'M', 'Age': 22, 'Height': 175, 'Country': 'Ukraine'}
]

df3 = pd.DataFrame(data_records)
print("\nMethod 3 (List of dicts):\n", df3)

# sample dataframe
data = {'LAST NAME': ['Smith', 'Garcia'],
        'FIRST NAME': ['John', 'Huan'],
        'SEX': ['M', 'M'],
        'AGE' : [34, 70] ,
        'HEIGHT' : [186, 160],
        'COUNTRY' : ['Australia', 'Spain']}

df = pd.DataFrame.from_dict(data)
df

,LAST NAME,FIRST NAME,SEX,AGE,HEIGHT,COUNTRY
0,Smith,John,M,34,186,Australia
1,Garcia,Huan,M,70,160,Spain


2️⃣  Навчіться виводити
1) перші рядки таблиці (df.head());
2) рядок із вказаним індексом (df.loc[i]);
3) вибірку стовпців (наприклад, 'LAST NAME', 'FIRST NAME', 'COUNTRY')
4) рядки за деякими умовами (наприклад, усіх іспанців, молодших 50 років або усіх жінок, вищіх за 190 см)


Проілюструйте дію функцій прикладами.

In [ ]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'LAST NAME': ['Smith', 'Garcia', 'Miller', 'Davis', 'Lopez'],
    'FIRST NAME': ['John', 'Maria', 'Anna', 'James', 'Elena'],
    'GENDER': ['M', 'F', 'F', 'M', 'F'],
    'AGE': [55, 34, 25, 42, 28],
    'HEIGHT': [180, 165, 192, 175, 195],
    'COUNTRY': ['USA', 'Spain', 'Germany', 'USA', 'Spain']
}
df = pd.DataFrame(data)

# 1. Display the first rows (default is 5)
print("--- First rows (head) ---")
print(df.head(3))

# 2. Display a row with a specific index (e.g., index 1)
print("\n--- Row with index 1 ---")
print(df.loc[1])

# 3. Select specific columns
print("\n--- Column selection ---")
selected_columns = df[['LAST NAME', 'FIRST NAME', 'COUNTRY']]
print(selected_columns)

# 4. Filter rows based on conditions
print("\n--- Filtering: Spanish people under 50 ---")
spanish_under_50 = df[(df['COUNTRY'] == 'Spain') & (df['AGE'] < 50)]
print(spanish_under_50)

print("\n--- Filtering: Women taller than 190 cm ---")
tall_women = df[(df['GENDER'] == 'F') & (df['HEIGHT'] > 190)]
print(tall_women)

3️⃣ Навчиться агрегувати дані за стовпчиками:
1. Знайдіть середній зріст усіх людей;
2. Знайдіть людину(людей) макcимального віку;
3. Знайдіть, скільки представників кожної країни присутні в таблиці (value_counts())

In [ ]:
import pandas as pd

# Creating sample data
data = {
    'Last_Name': ['Smith', 'Garcia', 'Miller', 'Davis', 'Lopez'],
    'First_Name': ['John', 'Maria', 'Anna', 'James', 'Elena'],
    'Age': [25, 45, 60, 60, 32],
    'Height': [180, 165, 170, 190, 175],
    'Country': ['USA', 'Spain', 'Germany', 'USA', 'Spain']
}
df = pd.DataFrame(data)

# 1. Find the average height of all people
average_height = df['Height'].mean()
print(f"Average height: {average_height}")

# 2. Find the person (or people) with the maximum age
max_age = df['Age'].max()
oldest_people = df[df['Age'] == max_age]
print("\nPerson(s) with maximum age:")
print(oldest_people)

# 3. Count how many representatives from each country are in the table
country_counts = df['Country'].value_counts()
print("\nRepresentatives per country:")
print(country_counts)

💻 **1.6. Рейтинг.**  У цій задачі ви складете найпростіший рейтинг студентів за допомогою множення матриць. Виконайте наступні кроки:

1️⃣  Складіть таблицю з відомостями про успішність студентів (близько 50 осіб), яка містить  номер залікової книжки студента, прізвище та ім'я, номер групи, оцінки з наступних предметів: Calculus, Algebra, C++ programming, Algorithms, а також відомості про позанавчальну діяльність: Science, Sport, Social. Оцінки з предметів, а також оцінки позанавчальної діяльності студентів мають бути надані за 100-бальною шкалою. Ви можете використати ШІ для створення такої таблиці, знайти готові дані або ж придумати власний спосіб заповнення. Мінімізуйте кількість ручної роботи.

In [31]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# 1. Define the number of students
num_students = 50

# 2. Generate IDs (e.g., MF_2025_01 to MF_2025_50)
ids = [f"MF_2025_{i:02d}" for i in range(1, num_students + 1)]

# 3. List of sample names (to make it look realistic)
first_names = ['Alan', 'Grace', 'Linus', 'Ada', 'Guido', 'Margaret', 'Ken', 'Barbara']
last_names = ['Turing', 'Hopper', 'Torvalds', 'Lovelace', 'Van Rossum', 'Hamilton', 'Thompson', 'Liskov']
names = [f"{np.random.choice(last_names)} {np.random.choice(first_names)} {np.random.choice(['A.', 'B.', 'M.', 'J.'])}"
         for _ in range(num_students)]

# 4. Assign groups
groups = np.random.choice(['MF11', 'MF12', 'MF13'], size=num_students)

# 5. Generate random scores (0-100) for Academic subjects
# We use integers for better readability
academic_scores = np.random.randint(60, 101, size=(num_students, 4)) # Subjects: Calculus, Algebra, C++, Algorithms

# 6. Generate random scores (0-100) for Extra-curricular activities
activity_scores = np.random.randint(0, 101, size=(num_students, 3)) # Science, Sport, Social

# 7. Create the DataFrame
columns = ['ID', 'NAME', 'GROUP', 'CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS', 'SCIENCE', 'SPORT', 'SOCIAL']

# Combine all data
all_data = np.column_stack((ids, names, groups, academic_scores, activity_scores))

activity = pd.DataFrame(all_data, columns=columns)

# Convert score columns back to numeric types
score_columns = columns[3:]
activity[score_columns] = activity[score_columns].apply(pd.to_numeric)

# Display the first few rows
print(activity.head())

# Check the total count
print(f"\nTotal students: {len(activity)}")


           ID                 NAME GROUP  CALCULUS  ALGEBRA  C++  ALGORITHMS  \
0  MF_2025_01      Thompson Ada A.  MF13        74       88   95          72   
1  MF_2025_02    Thompson Linus J.  MF13        91       66   81          87   
2  MF_2025_03  Van Rossum Guido M.  MF11        61       65   87          87   
3  MF_2025_04      Hopper Linus M.  MF13        79       89   70          87   
4  MF_2025_05    Torvalds Linus J.  MF11        84       98   92          60   

   SCIENCE  SPORT  SOCIAL  
0       92     41      25  
1       98     49      24  
2       23     12      59  
3        6     56      35  
4       44     19      64  

Total students: 50


2️⃣  Деканат ухвалив рішення, що цього семестру при складанні стипендіального рейтингу найважливіше значення матимуть спеціальні предмети ('C++', 'ALGORITHMS'), а також наукова активність студентів ( 'SCIENCE'), і визначив рейтингові коєфіцієнти: 'CALCULUS' 0.15; 'ALGEBRA' 0.15; 'C++' 0.2; 'ALGORITHMS' 0.2; 'SCIENCE' 0.2; 'SPORT' 0.05, 'SOCIAL' 0.05. Наприклад, підсумковий рейтинг ('SCORE') студента  Turing Alan M. складатиме $0.15\cdot 70+0.15\cdot 95+0.2\cdot 80 +0.2\cdot 95+0.05\cdot 10 + 0.05\cdot 0=80.25$
  
Складіть вектор рейтингових коефіцієнтів $w$ (ваговий вектор). Зробіть виборку з оцінками з таблиці activity і збережіть у вигляді numpy-масиву values.

In [ ]:
import numpy as np
#write your code here
#weights vector
w = np.array([0.15, 0.15, 0.2, 0.2, 0.2, 0.05, 0.05])

values = np.array(activity[['CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS', 'SCIENCE', 'SPORT', 'SOCIAL']])

scores = values @ w



3️⃣ Обчисліть рейтинги студентів ('SCORE') за допомогою матрично-векторного множення. Додайте стовпчик 'SCORE' до таблиці activity та відсортуйте студентів за цим стовпцем.

In [34]:
#write your code here
# Если нужно добавить результат обратно в таблицу activity:
activity['SCORE'] = scores

# 4. Sort students by the 'SCORE' column in descending order (highest score first)
activity = activity.sort_values(by='SCORE', ascending=False)

# Display the top 5 students
print("Top 5 students by score:")
print(activity[['NAME', 'GROUP', 'SCORE']].head())

NameError: name 'weights' is not defined

4️⃣ Напишіть функції, які дозволяють за таблицею оцінок і вектором рейтингових коефіцієнтів

 + знаходити рейтинги усіх студентів і виводити його у вигляді таблиці або словника;
 + знаходити рейгинги студентів окремо за групами;
 + знаходити середній бал студентів окремо за предметами, окремо за позанавчальними активностями.

Використайте матрично-векторні вирази.

5️⃣ Протестуйте ваші функції й продемонструйте, як вони працюють. Наприклад, виведіть рейтинги окремо за кожною групою, змінюйте ваговий вектор, нарахуйте за рейтингом стипендію (перші 5% отримують підвищену стипендію, наступні 20% -- звичайну, інші -- не отримують), тощо.

In [35]:
#write your code here
import numpy as np
import pandas as pd

# Function 1: Calculate ratings for all students using matrix-vector multiplication
def get_all_ratings(df, weights_vector):
    # Select only numeric score columns for calculation
    score_cols = ['CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS', 'SCIENCE', 'SPORT', 'SOCIAL']
    scores_matrix = df[score_cols].values

    # Matrix-vector multiplication to get ratings
    df['SCORE'] = scores_matrix @ weights_vector
    return df[['ID', 'NAME', 'GROUP', 'SCORE']]

# Function 2: Get ratings grouped by specific groups
def get_ratings_by_group(df):
    # Returns a dictionary where keys are group names and values are DataFrames
    groups = df['GROUP'].unique()
    return {group: df[df['GROUP'] == group].sort_values(by='SCORE', ascending=False) for group in groups}

# Function 3: Calculate average scores for subjects and activities separately
def get_average_scores(df):
    academic_cols = ['CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS']
    activity_cols = ['SCIENCE', 'SPORT', 'SOCIAL']

    return {
        'academic_averages': df[academic_cols].mean(),
        'activity_averages': df[activity_cols].mean()
    }

# --- TESTING AND DEMONSTRATION (Task 5) ---

# 1. Initialize weights
weights = np.array([0.15, 0.15, 0.2, 0.2, 0.2, 0.05, 0.05])

# 2. Calculate initial ratings
ratings_df = get_all_ratings(activity, weights)

# 3. Calculate scholarships based on ratings
# Top 5% -> Increased, Next 20% -> Regular, Others -> None
activity = activity.sort_values(by='SCORE', ascending=False).reset_index(drop=True)
num_students = len(activity)

increased_threshold = int(num_students * 0.05)
regular_threshold = int(num_students * 0.25) # 5% + 20%

activity['SCHOLARSHIP'] = 'None'
activity.iloc[:increased_threshold, activity.columns.get_loc('SCHOLARSHIP')] = 'Increased'
activity.iloc[increased_threshold:regular_threshold, activity.columns.get_loc('SCHOLARSHIP')] = 'Regular'

# 4. Demonstrate results
print("--- Average Scores ---")
averages = get_average_scores(activity)
print(averages['academic_averages'])

print("\n--- Ratings for Group MF11 (Top 3) ---")
grouped_ratings = get_ratings_by_group(activity)
print(grouped_ratings['MF11'][['NAME', 'SCORE', 'SCHOLARSHIP']].head(3))

print("\n--- Scholarship Distribution ---")
print(activity['SCHOLARSHIP'].value_counts())


--- Average Scores ---
CALCULUS      83.44
ALGEBRA       79.38
C++           82.08
ALGORITHMS    80.68
dtype: float64

--- Ratings for Group MF11 (Top 3) ---
                    NAME  SCORE SCHOLARSHIP
0      Hamilton Grace B.  87.95   Increased
14      Lovelace Alan A.  77.00        None
22  Lovelace Margaret B.  73.15        None

--- Scholarship Distribution ---
SCHOLARSHIP
None         38
Regular      10
Increased     2
Name: count, dtype: int64


💻 **1.7. Маркетингова кампанія.** Компанія влаштовує рекламну кампанію своєї продукції. Для цього усіх потенційних клієнтів поділено на $m$ груп (кожна група характеризується спільними характеристиками, наприклад, чоловіки 35-45 років з вищою освітою або жінки-домогосподині віком понад 60, тощо). Компанія замовляє рекламу продукції за $n$ каналами (наприклад, на телебаченні, на веб-сайтах, у відео-блогах, поштою тощо). Здатність каналів забезпечити перегляди потенційних клієнтів характризується $m\times n$ *матрицей охоплення*  $R=(R_{ij})$, де $R_{ij}$ -- це кількість переглядів клієнтів із групи $i$ на кожен долар (або іншу грошову одиницю), витрачений на рекламу в каналі $j$. Наприклад, якщо на рекламу на ТБ-шоу (канал 1) було витрачено 1000 доларів і це шоу подивилось 30 000 домогосподарок пенсійного віку (група 1) і 5 студентів-чоловіків віком до 25 років (група 2), то $R_{11}=30$, $R_{21} = 0.005$.

Нехай вектор $c$ з $n$ компонентами характеризує витрати компанії на рекламу за $n$ каналами, а вектор $v$ з $m$ компонентами характеризує охоплення кожної з $m$ груп клієнтів за всіма каналами реклами, тобто $v_i$ -- це загальна кількість переглядів реклами за всіма каналами клієнтами з групи $i$. Також розглянемо вектор  $a$ з $m$ компонентами, для якого $a_i$ дорівнює доходу (в доларах) на один перегляд реклами клієнтом з групи $i$. Зауважимо, що всі елементи  $R, c, v, a$ є невід'ємними числами.

Задайте власні приклади матриці $R$ і векторів $c, a$. Можете використати штучний інтелект для генерації, або ж вигадати щось своє. Намагайтеся зробити дані реалістичними.

In [36]:
#write your code here
import numpy as np

# --- Initialization ---
# Let m = 4 groups of clients and n = 3 advertising channels
m, n = 4, 3

# R (m x n): Reach matrix (views per dollar)
# Rows: Client groups, Columns: Channels
R = np.array([
    [30.0, 10.0, 5.0],   # Group 1: Seniors
    [0.005, 50.0, 20.0],  # Group 2: Students
    [15.0, 5.0, 40.0],   # Group 3: Parents
    [10.0, 15.0, 10.0]    # Group 4: Professionals
])

# c (n): Advertising costs per channel
costs_c = np.array([1000, 500, 1200])

# a (m): Income (in dollars) per one view for each client group
income_per_view_a = np.array([0.05, 0.01, 0.10, 0.08])

# --- Task 1: Total Spending ---
# Formula: Sum of components of vector c, or 1^T * c
ones_n = np.ones(n)
total_spending = ones_n.T @ costs_c
print(f"1. Total spending on advertising: ${total_spending:.2f}")

# --- Task 2: Reach Vector (v) ---
# Formula: v = R * c
# v characterizes total views per client group across all channels
reach_v = R @ costs_c
print(f"\n2. Total reach vector (v):\n{reach_v}")

# --- Task 3: Total Income ---
# Formula: Total Income = a^T * v = a^T * (R * c)
total_income = income_per_view_a.T @ reach_v
print(f"\n3. Total expected income: ${total_income:.2f}")

# --- Task 4: Best Channel for Each Group ---
# Find the index of the maximum value in each row of matrix R
best_channels = np.argmax(R, axis=1)

print("\n4. Most effective channels per group:")
for group_idx, channel_idx in enumerate(best_channels):
    print(f"   Group {group_idx + 1}: Channel {channel_idx + 1} "
          f"(Reach: {R[group_idx, channel_idx]} views/$)")


1. Total spending on advertising: $2700.00

2. Total reach vector (v):
[41000. 49005. 65500. 29500.]

3. Total expected income: $11450.05

4. Most effective channels per group:
   Group 1: Channel 1 (Reach: 30.0 views/$)
   Group 2: Channel 2 (Reach: 50.0 views/$)
   Group 3: Channel 3 (Reach: 40.0 views/$)
   Group 4: Channel 2 (Reach: 15.0 views/$)


1️⃣  Розглянемо векторний вираз, за яким можна знайти загальну кількість грошей, що компанія витрачає на рекламу. Це має бути сума усіх компонент вектора $c$. За допомогою матрично-векторного запису цю суму можна подати як $1^t c$, де $1$ -- це вектор з  $n$ компонентами, кожна з яких дорівнює 1, $t$ означає транспонування, тобто $1^t$ -- це вектор-рядок з одиниць.

Обчисліть, скільки ця сума складає у вашому випадку за допомогою отриманого виразу.

In [ ]:
#write your code here

2️⃣  Виразіть вектор $v$ через інші вектори й матриці, задані в задачі. Обчисліть його.

✔️ *Запишіть аналітичний вираз тут*

In [ ]:
#write your code here

3️⃣ Запишіть вираз, за яким можна знайти загальний дохід, що отримає компанія, застосовуючи рекламу. Обчисліть дохід.

✔️ *Запишіть аналітичний вираз тут*

In [ ]:
#write your code here

4️⃣  За матрицею $R$ знайдіть для кожної групи клієнтів той канал, який здійснює найбільше охоплення клієнтів цієї групи (на ньому вигідніше розміщувати рекламу)

In [ ]:
#write your code here